CFLAGS += -I$(srctree)/inc/MST9U/board -I$(srctree)/src
AFLAGS += -I$(srctree)/inc/MST9U/board -I$(srctree)/src

extra-$(CONFIG_MSTAR_MST9U) 		+= sboot.lds

lib-$(CONFIG_MSTAR_MST9U) 		+= reset.o
lib-$(CONFIG_MSTAR_MST9U) 		+= cache.o
lib-$(CONFIG_MSTAR_MST9U) 		+= context.o
lib-$(CONFIG_MSTAR_MST9U) 		+= backtrace.o
lib-$(CONFIG_MSTAR_MST9U) 		+= exception.o
lib-$(CONFIG_MSTAR_MST9U) 		+= interrupt.o
lib-$(CONFIG_MSTAR_MST9U) 		+= risc32.o
lib-$(CONFIG_MSTAR_MST9U) 		+= stack.o
lib-$(CONFIG_MSTAR_MST9U) 		+= vectors.o
lib-$(CONFIG_MSTAR_MST9U) 		+= init_MST9U.o
lib-$(CONFIG_MSTAR_MST9U) 		+= drvGlobal.o
lib-$(CONFIG_MSTAR_MST9U) 		+= bootaeonsysinit.o
lib-$(CONFIG_MSTAR_MST9U) 		+= puts.o
lib-$(CONFIG_MSTAR_MST9U) 		+= printf.o
lib-$(CONFIG_MSTAR_MST9U) 		+= drvAeonUART.o
lib-$(CONFIG_MSTAR_MST9U) 		+= vsnprintf.o
lib-$(CONFIG_MSTAR_MST9U) 		+= snprintf.o
#lib-$(CONFIG_MSTAR_MST9U) 		+= sprintf.o
#lib-$(CONFIG_MSTAR_MST9U) 		+= device.o
#lib-$(CONFIG_MSTAR_MST9U) 		+= putchar.o
lib-$(CONFIG_MSTAR_MST9U) 		+= drvPadConf.o
lib-$(CONFIG_MSTAR_MST9U) 		+= setSPI.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ddr_bd_mst203a_a01a_etron_1333.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ddr_bd_mst203a_a01a_winbond_1333.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ddr_bd_mst203a_a01a_esmt_1333.o

ifeq ($(CONFIG_USB),y)
lib-$(CONFIG_MSTAR_MST9U) 		+= timer_cb.o
lib-$(CONFIG_MSTAR_MST9U) 		+= memset.o
lib-$(CONFIG_MSTAR_MST9U) 		+= malloc-bsd.o
lib-$(CONFIG_MSTAR_MST9U) 		+= sbrk.o

lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/Utl.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/MsFlash.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/mw_usbdownload.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/MApp_SwUpdate.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/MApp_USBDownload.o

lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/msAPI_Memory.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/IOUtil.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/msAPI_FS_SysInfo.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/msAPI_FCtrl.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/msAPI_FAT.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/FAT_Cache.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/FSUtil.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/msAPI_MSDCtrl.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/msAPI_FSEnv.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/msAPI_N51FS.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/N51FS_File.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/N51FS_Index.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/N51FS_Bitmap.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/drvHost200.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/drvUsbHostLib.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/drvHostLib.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/drvMassStorage.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/drvScsi.o
lib-$(CONFIG_MSTAR_MST9U) 		+= ./usb/drvUsbMain.o
endif

