// Dell_199WFP_test
// 07-11-2007 : 09:32:32

// This file is automatically generated by OneTouch Studio
// This file is very specific to a design

// ******************************************
// ******************************************
// ==> WARNING: ** DO NOT EDIT This file <== 
// ******************************************
// ******************************************

#ifdef		OT_LIB_VER_4_ABOVE
					// NOTE: For OTLib 4.0 or above

#ifndef _OTCONFIG_H
#define _OTCONFIG_H

#include "OTCore.h"

//#define	OT_ADDR							0x58//0x2C	// OneTouch Device I2C Slave Address

// OneTouch Register Definitions

#define OT_CONFIG_REG_START_ADDR		0x0000
#define OT_CONFIG_REG_END_ADDR			0x0018
#define OT_NUM_CONFIG_REG_BYTES			((OT_CONFIG_REG_END_ADDR - OT_CONFIG_REG_START_ADDR + 1)*2)
									// Total number of Configuration Bytes

#define OT_DATA_REG_START_ADDR			0x0108
#define OT_DATA_REG_END_ADDR			0x0109
#define OT_NUM_DATA_REG_BYTES			((OT_DATA_REG_END_ADDR - OT_DATA_REG_START_ADDR + 1)*2)
									// Total number of Data Bytes

#define	OT_DATA_REG_START_ADDR_HIGH		((OT_DATA_REG_START_ADDR & 0xFF00)>>8)
#define	OT_DATA_REG_START_ADDR_LOW		(OT_DATA_REG_START_ADDR & 0x00FF)


#define OT_BUTTON_DATA_REG_OFFSET		2
#define OT_BUTTON_HIGH_ELECTRODE		4
#define OT_BUTTON_LOW_ELECTRODE			15


#define OT_GPI_DATA_REG_OFFSET			0
#define OT_GPI_HIGH_ELECTRODE			3
#define OT_GPI_LOW_ELECTRODE			4


#define OT_CONFIG_TABLE_ROWS			7

BYTE OT_Config_Table[OT_CONFIG_TABLE_ROWS][4] = {
// {address-high-byte, address-low-byte, data-hi-byte, data-lo-byte }
{ 0x00, 0x00, 0x00, 0x04 },
{ 0x00, 0x01, 0x00, 0x04 },
{ 0x00, 0x04, 0x90, 0x90 },
{ 0x00, 0x12, 0x00, 0x98 },
{ 0x00, 0x13, 0x8E, 0x85 },
{ 0x00, 0x16, 0x84, 0x87 },
{ 0x00, 0x17, 0x95, 0x00 },
{ 0x00, 0x0E, 0x1F, 0x00 }
};

#endif

#else
			// NOTE: For OTLib 3.0 or earlier

#ifndef _SYNAOTCONFIG_H
#define _SYNAOTCONFIG_H

#include "SynaOT.h"

//#define OT_ADDR							0x58//0x2C	// OneTouch Device I2C Slave Address

// OneTouch Register Definitions

#define OT_CONFIG_REG_START_ADDR		0x0000
#define OT_CONFIG_REG_END_ADDR			0x002B
#define OT_NUM_CONFIG_REG_BYTES			((OT_CONFIG_REG_END_ADDR - OT_CONFIG_REG_START_ADDR + 1)*2)
										// Total number of Configuration Bytes
#define OT_NUM_CONFIG_BYTES				(OT_NUM_CONFIG_REG_BYTES + 2)



#endif

#endif