/*
 * Automatically generated C config: don't edit
 * SBoot version: 1.0.0
 */
#define AUTOCONF_TIMESTAMP "2015-05-07 21:22:13 CST"

#define CONFIG_HAVE_DOT_CONFIG 1
#define ENABLE_HAVE_DOT_CONFIG 1
#define USE_HAVE_DOT_CONFIG(...) __VA_ARGS__
#define SKIP_HAVE_DOT_CONFIG(...)

/*
 * Platform Configuration
 */
#define CONFIG_MSTAR_MST9U 1
#define ENABLE_MSTAR_MST9U 1
#define USE_MSTAR_MST9U(...) __VA_ARGS__
#define SKIP_MSTAR_MST9U(...)
#undef CONFIG_MSTAR_AMBER7
#define ENABLE_MSTAR_AMBER7 0
#define USE_MSTAR_AMBER7(...)
#define SKIP_MSTAR_AMBER7(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12
#define ENABLE_MSTAR_MACAW12 0
#define USE_MSTAR_MACAW12(...)
#define SKIP_MSTAR_MACAW12(...) __VA_ARGS__
#define CONFIG_MSTAR_CHIP_NAME "MST9U"
#define ENABLE_MSTAR_CHIP_NAME 1
#define USE_MSTAR_CHIP_NAME(...) __VA_ARGS__
#define SKIP_MSTAR_CHIP_NAME(...)
#undef CONFIG_MCU_MIPS32
#define ENABLE_MCU_MIPS32 0
#define USE_MCU_MIPS32(...)
#define SKIP_MCU_MIPS32(...) __VA_ARGS__
#undef CONFIG_MCU_ARM
#define ENABLE_MCU_ARM 0
#define USE_MCU_ARM(...)
#define SKIP_MCU_ARM(...) __VA_ARGS__
#define CONFIG_MCU_AEONR2 1
#define ENABLE_MCU_AEONR2 1
#define USE_MCU_AEONR2(...) __VA_ARGS__
#define SKIP_MCU_AEONR2(...)
#define CONFIG_BOOTING_FROM_EXT_SPI_WITH_CPU 1
#define ENABLE_BOOTING_FROM_EXT_SPI_WITH_CPU 1
#define USE_BOOTING_FROM_EXT_SPI_WITH_CPU(...) __VA_ARGS__
#define SKIP_BOOTING_FROM_EXT_SPI_WITH_CPU(...)
#undef CONFIG_BOOTING_FROM_EXT_SPI_WITH_PM51
#define ENABLE_BOOTING_FROM_EXT_SPI_WITH_PM51 0
#define USE_BOOTING_FROM_EXT_SPI_WITH_PM51(...)
#define SKIP_BOOTING_FROM_EXT_SPI_WITH_PM51(...) __VA_ARGS__
#undef CONFIG_BOOTING_FROM_OTP_WITH_PM51
#define ENABLE_BOOTING_FROM_OTP_WITH_PM51 0
#define USE_BOOTING_FROM_OTP_WITH_PM51(...)
#define SKIP_BOOTING_FROM_OTP_WITH_PM51(...) __VA_ARGS__
#undef CONFIG_CPU_345MHZ
#define ENABLE_CPU_345MHZ 0
#define USE_CPU_345MHZ(...)
#define SKIP_CPU_345MHZ(...) __VA_ARGS__
#define CONFIG_CPU_320MHZ 1
#define ENABLE_CPU_320MHZ 1
#define USE_CPU_320MHZ(...) __VA_ARGS__
#define SKIP_CPU_320MHZ(...)
#undef CONFIG_CPU_288MHZ
#define ENABLE_CPU_288MHZ 0
#define USE_CPU_288MHZ(...)
#define SKIP_CPU_288MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_240MHZ
#define ENABLE_CPU_240MHZ 0
#define USE_CPU_240MHZ(...)
#define SKIP_CPU_240MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_216MHZ
#define ENABLE_CPU_216MHZ 0
#define USE_CPU_216MHZ(...)
#define SKIP_CPU_216MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_192MHZ
#define ENABLE_CPU_192MHZ 0
#define USE_CPU_192MHZ(...)
#define SKIP_CPU_192MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_144MHZ
#define ENABLE_CPU_144MHZ 0
#define USE_CPU_144MHZ(...)
#define SKIP_CPU_144MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_108MHZ
#define ENABLE_CPU_108MHZ 0
#define USE_CPU_108MHZ(...)
#define SKIP_CPU_108MHZ(...) __VA_ARGS__
#undef CONFIG_MSTAR_MANUAL
#define ENABLE_MSTAR_MANUAL 0
#define USE_MSTAR_MANUAL(...)
#define SKIP_MSTAR_MANUAL(...) __VA_ARGS__
#define CONFIG_MSTAR_OTHERS 0
#define ENABLE_MSTAR_OTHERS 1
#define USE_MSTAR_OTHERS(...) __VA_ARGS__
#define SKIP_MSTAR_OTHERS(...)
#undef CONFIG_MSTAR_BD_FPGA
#define ENABLE_MSTAR_BD_FPGA 0
#define USE_MSTAR_BD_FPGA(...)
#define SKIP_MSTAR_BD_FPGA(...) __VA_ARGS__
#define CONFIG_MSTAR_MST9U_BD_MSTxxxA_DxxA_S 1
#define ENABLE_MSTAR_MST9U_BD_MSTxxxA_DxxA_S 1
#define USE_MSTAR_MST9U_BD_MSTxxxA_DxxA_S(...) __VA_ARGS__
#define SKIP_MSTAR_MST9U_BD_MSTxxxA_DxxA_S(...)
#undef CONFIG_PNL_FULLHD_SEC_LE32A
#define ENABLE_PNL_FULLHD_SEC_LE32A 0
#define USE_PNL_FULLHD_SEC_LE32A(...)
#define SKIP_PNL_FULLHD_SEC_LE32A(...) __VA_ARGS__
#undef CONFIG_PNL_SXGA_AU17_EN05
#define ENABLE_PNL_SXGA_AU17_EN05 0
#define USE_PNL_SXGA_AU17_EN05(...)
#define SKIP_PNL_SXGA_AU17_EN05(...) __VA_ARGS__
#define CONFIG_PNL_WXGA_AU20_T200XW02 1
#define ENABLE_PNL_WXGA_AU20_T200XW02 1
#define USE_PNL_WXGA_AU20_T200XW02(...) __VA_ARGS__
#define SKIP_PNL_WXGA_AU20_T200XW02(...)
#undef CONFIG_PNL_WXGA_PLUS_CMO190_M190A1
#define ENABLE_PNL_WXGA_PLUS_CMO190_M190A1 0
#define USE_PNL_WXGA_PLUS_CMO190_M190A1(...)
#define SKIP_PNL_WXGA_PLUS_CMO190_M190A1(...) __VA_ARGS__
#undef CONFIG_PNL_WSXGA_AU22_M201EW01
#define ENABLE_PNL_WSXGA_AU22_M201EW01 0
#define USE_PNL_WSXGA_AU22_M201EW01(...)
#define SKIP_PNL_WSXGA_AU22_M201EW01(...) __VA_ARGS__
#undef CONFIG_PNL_FULLHD_CMO216_H1L01
#define ENABLE_PNL_FULLHD_CMO216_H1L01 0
#define USE_PNL_FULLHD_CMO216_H1L01(...)
#define SKIP_PNL_FULLHD_CMO216_H1L01(...) __VA_ARGS__
#undef CONFIG_PANEL_RES_FULL_HD
#define ENABLE_PANEL_RES_FULL_HD 0
#define USE_PANEL_RES_FULL_HD(...)
#define SKIP_PANEL_RES_FULL_HD(...) __VA_ARGS__
#undef CONFIG_PNL_WUXGA_CMO260_J2
#define ENABLE_PNL_WUXGA_CMO260_J2 0
#define USE_PNL_WUXGA_CMO260_J2(...)
#define SKIP_PNL_WUXGA_CMO260_J2(...) __VA_ARGS__
#undef CONFIG_MFC120_FULLHD_CMO216_H1L01
#define ENABLE_MFC120_FULLHD_CMO216_H1L01 0
#define USE_MFC120_FULLHD_CMO216_H1L01(...)
#define SKIP_MFC120_FULLHD_CMO216_H1L01(...) __VA_ARGS__
#undef CONFIG_MFC60_FULLHD_CMO216_H1L01
#define ENABLE_MFC60_FULLHD_CMO216_H1L01 0
#define USE_MFC60_FULLHD_CMO216_H1L01(...)
#define SKIP_MFC60_FULLHD_CMO216_H1L01(...) __VA_ARGS__
#undef CONFIG_PNL_FULLHD_TCON
#define ENABLE_PNL_FULLHD_TCON 0
#define USE_PNL_FULLHD_TCON(...)
#define SKIP_PNL_FULLHD_TCON(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_576I
#define ENABLE_PNL_DACOUT_576I 0
#define USE_PNL_DACOUT_576I(...)
#define SKIP_PNL_DACOUT_576I(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_576P
#define ENABLE_PNL_DACOUT_576P 0
#define USE_PNL_DACOUT_576P(...)
#define SKIP_PNL_DACOUT_576P(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_720P_50
#define ENABLE_PNL_DACOUT_720P_50 0
#define USE_PNL_DACOUT_720P_50(...)
#define SKIP_PNL_DACOUT_720P_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080I_50
#define ENABLE_PNL_DACOUT_1080I_50 0
#define USE_PNL_DACOUT_1080I_50(...)
#define SKIP_PNL_DACOUT_1080I_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080P_50
#define ENABLE_PNL_DACOUT_1080P_50 0
#define USE_PNL_DACOUT_1080P_50(...)
#define SKIP_PNL_DACOUT_1080P_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_480I
#define ENABLE_PNL_DACOUT_480I 0
#define USE_PNL_DACOUT_480I(...)
#define SKIP_PNL_DACOUT_480I(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_480P
#define ENABLE_PNL_DACOUT_480P 0
#define USE_PNL_DACOUT_480P(...)
#define SKIP_PNL_DACOUT_480P(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_720P_60
#define ENABLE_PNL_DACOUT_720P_60 0
#define USE_PNL_DACOUT_720P_60(...)
#define SKIP_PNL_DACOUT_720P_60(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080I_60
#define ENABLE_PNL_DACOUT_1080I_60 0
#define USE_PNL_DACOUT_1080I_60(...)
#define SKIP_PNL_DACOUT_1080I_60(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080P_60
#define ENABLE_PNL_DACOUT_1080P_60 0
#define USE_PNL_DACOUT_1080P_60(...)
#define SKIP_PNL_DACOUT_1080P_60(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT
#define ENABLE_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT 0
#define USE_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT(...)
#define SKIP_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT(...) __VA_ARGS__
#define CONFIG_MSTAR_MST9U_MMAP_512MB 1
#define ENABLE_MSTAR_MST9U_MMAP_512MB 1
#define USE_MSTAR_MST9U_MMAP_512MB(...) __VA_ARGS__
#define SKIP_MSTAR_MST9U_MMAP_512MB(...)
#undef CONFIG_MSTAR_MST9U_MMAP_256MB
#define ENABLE_MSTAR_MST9U_MMAP_256MB 0
#define USE_MSTAR_MST9U_MMAP_256MB(...)
#define SKIP_MSTAR_MST9U_MMAP_256MB(...) __VA_ARGS__
#define CONFIG_MEM2133MHz 1
#define ENABLE_MEM2133MHz 1
#define USE_MEM2133MHz(...) __VA_ARGS__
#define SKIP_MEM2133MHz(...)
#undef CONFIG_MEM1866MHz
#define ENABLE_MEM1866MHz 0
#define USE_MEM1866MHz(...)
#define SKIP_MEM1866MHz(...) __VA_ARGS__
#undef CONFIG_MEM1333MHz
#define ENABLE_MEM1333MHz 0
#define USE_MEM1333MHz(...)
#define SKIP_MEM1333MHz(...) __VA_ARGS__
#undef CONFIG_MEM1600MHz
#define ENABLE_MEM1600MHz 0
#define USE_MEM1600MHz(...)
#define SKIP_MEM1600MHz(...) __VA_ARGS__
#undef CONFIG_MEM1300MHz
#define ENABLE_MEM1300MHz 0
#define USE_MEM1300MHz(...)
#define SKIP_MEM1300MHz(...) __VA_ARGS__
#undef CONFIG_MEM1066MHz
#define ENABLE_MEM1066MHz 0
#define USE_MEM1066MHz(...)
#define SKIP_MEM1066MHz(...) __VA_ARGS__
#undef CONFIG_DDR3_16BIT_MODE
#define ENABLE_DDR3_16BIT_MODE 0
#define USE_DDR3_16BIT_MODE(...)
#define SKIP_DDR3_16BIT_MODE(...) __VA_ARGS__
#undef CONFIG_DDR3_8BIT_MODE
#define ENABLE_DDR3_8BIT_MODE 0
#define USE_DDR3_8BIT_MODE(...)
#define SKIP_DDR3_8BIT_MODE(...) __VA_ARGS__
#undef CONFIG_MIU0_DRAM_NONE
#define ENABLE_MIU0_DRAM_NONE 0
#define USE_MIU0_DRAM_NONE(...)
#define SKIP_MIU0_DRAM_NONE(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR3_1666
#define ENABLE_MIU0_DDR3_1666 0
#define USE_MIU0_DDR3_1666(...)
#define SKIP_MIU0_DDR3_1666(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR3_1333
#define ENABLE_MIU0_DDR3_1333 0
#define USE_MIU0_DDR3_1333(...)
#define SKIP_MIU0_DDR3_1333(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR3_1066
#define ENABLE_MIU0_DDR3_1066 0
#define USE_MIU0_DDR3_1066(...)
#define SKIP_MIU0_DDR3_1066(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR2_1066
#define ENABLE_MIU0_DDR2_1066 0
#define USE_MIU0_DDR2_1066(...)
#define SKIP_MIU0_DDR2_1066(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR2_800
#define ENABLE_MIU0_DDR2_800 0
#define USE_MIU0_DDR2_800(...)
#define SKIP_MIU0_DDR2_800(...) __VA_ARGS__
#undef CONFIG_MIU1_DRAM_NONE
#define ENABLE_MIU1_DRAM_NONE 0
#define USE_MIU1_DRAM_NONE(...)
#define SKIP_MIU1_DRAM_NONE(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR3_1666
#define ENABLE_MIU1_DDR3_1666 0
#define USE_MIU1_DDR3_1666(...)
#define SKIP_MIU1_DDR3_1666(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR3_1333
#define ENABLE_MIU1_DDR3_1333 0
#define USE_MIU1_DDR3_1333(...)
#define SKIP_MIU1_DDR3_1333(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR3_1066
#define ENABLE_MIU1_DDR3_1066 0
#define USE_MIU1_DDR3_1066(...)
#define SKIP_MIU1_DDR3_1066(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR2_1066
#define ENABLE_MIU1_DDR2_1066 0
#define USE_MIU1_DDR2_1066(...)
#define SKIP_MIU1_DDR2_1066(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR2_800
#define ENABLE_MIU1_DDR2_800 0
#define USE_MIU1_DDR2_800(...)
#define SKIP_MIU1_DDR2_800(...) __VA_ARGS__
#undef CONFIG_ENABLE_MIU_SWAP
#define ENABLE_ENABLE_MIU_SWAP 0
#define USE_ENABLE_MIU_SWAP(...)
#define SKIP_ENABLE_MIU_SWAP(...) __VA_ARGS__
#undef CONFIG_BIST_0x0401_UNITS
#define ENABLE_BIST_0x0401_UNITS 0
#define USE_BIST_0x0401_UNITS(...)
#define SKIP_BIST_0x0401_UNITS(...) __VA_ARGS__
#define CONFIG_BIST_0x1001_UNITS 1
#define ENABLE_BIST_0x1001_UNITS 1
#define USE_BIST_0x1001_UNITS(...) __VA_ARGS__
#define SKIP_BIST_0x1001_UNITS(...)
#undef CONFIG_BIST_0x8001_UNITS
#define ENABLE_BIST_0x8001_UNITS 0
#define USE_BIST_0x8001_UNITS(...)
#define SKIP_BIST_0x8001_UNITS(...) __VA_ARGS__
#define CONFIG_BOOTRAM_LOADADDR 0x01000000
#define ENABLE_BOOTRAM_LOADADDR 1
#define USE_BOOTRAM_LOADADDR(...) __VA_ARGS__
#define SKIP_BOOTRAM_LOADADDR(...)
#define CONFIG_UBOOT_LOADADDR 0x41200000
#define ENABLE_UBOOT_LOADADDR 1
#define USE_UBOOT_LOADADDR(...) __VA_ARGS__
#define SKIP_UBOOT_LOADADDR(...)
#define CONFIG_DRAM_SIZE_MB_RELOCATE 256
#define ENABLE_DRAM_SIZE_MB_RELOCATE 1
#define USE_DRAM_SIZE_MB_RELOCATE(...) __VA_ARGS__
#define SKIP_DRAM_SIZE_MB_RELOCATE(...)
#undef CONFIG_MSTAR_STR_ENABLE
#define ENABLE_MSTAR_STR_ENABLE 0
#define USE_MSTAR_STR_ENABLE(...)
#define SKIP_MSTAR_STR_ENABLE(...) __VA_ARGS__
#define CONFIG_PM_DRAM_ADDRESS 0x
#define ENABLE_PM_DRAM_ADDRESS 1
#define USE_PM_DRAM_ADDRESS(...) __VA_ARGS__
#define SKIP_PM_DRAM_ADDRESS(...)
#define CONFIG_CUSTOMER_KEY_BANK_DRAM_ADDRESS 0x
#define ENABLE_CUSTOMER_KEY_BANK_DRAM_ADDRESS 1
#define USE_CUSTOMER_KEY_BANK_DRAM_ADDRESS(...) __VA_ARGS__
#define SKIP_CUSTOMER_KEY_BANK_DRAM_ADDRESS(...)
#define CONFIG_SECURE_INFO_DRAM_ADDRESS 0x
#define ENABLE_SECURE_INFO_DRAM_ADDRESS 1
#define USE_SECURE_INFO_DRAM_ADDRESS(...) __VA_ARGS__
#define SKIP_SECURE_INFO_DRAM_ADDRESS(...)
#undef CONFIG_MSTAR_MOBF_ENABLE
#define ENABLE_MSTAR_MOBF_ENABLE 0
#define USE_MSTAR_MOBF_ENABLE(...)
#define SKIP_MSTAR_MOBF_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_ASIC_EMULATION_ENABLE
#define ENABLE_MSTAR_ASIC_EMULATION_ENABLE 0
#define USE_MSTAR_ASIC_EMULATION_ENABLE(...)
#define SKIP_MSTAR_ASIC_EMULATION_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_SINGLE_CORE
#define ENABLE_MSTAR_MIPS_SINGLE_CORE 0
#define USE_MSTAR_MIPS_SINGLE_CORE(...)
#define SKIP_MSTAR_MIPS_SINGLE_CORE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_DUAL_CORE
#define ENABLE_MSTAR_MIPS_DUAL_CORE 0
#define USE_MSTAR_MIPS_DUAL_CORE(...)
#define SKIP_MSTAR_MIPS_DUAL_CORE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_SINGLE_VPE_PER_CORE
#define ENABLE_MSTAR_MIPS_SINGLE_VPE_PER_CORE 0
#define USE_MSTAR_MIPS_SINGLE_VPE_PER_CORE(...)
#define SKIP_MSTAR_MIPS_SINGLE_VPE_PER_CORE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_DUAL_VPE_PER_CORE
#define ENABLE_MSTAR_MIPS_DUAL_VPE_PER_CORE 0
#define USE_MSTAR_MIPS_DUAL_VPE_PER_CORE(...)
#define SKIP_MSTAR_MIPS_DUAL_VPE_PER_CORE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5(...) __VA_ARGS__
#undef CONFIG_MSTAR_L2_CACHE_ENABLE
#define ENABLE_MSTAR_L2_CACHE_ENABLE 0
#define USE_MSTAR_L2_CACHE_ENABLE(...)
#define SKIP_MSTAR_L2_CACHE_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_CPU_PREFETCH_ENABLE
#define ENABLE_MSTAR_CPU_PREFETCH_ENABLE 0
#define USE_MSTAR_CPU_PREFETCH_ENABLE(...)
#define SKIP_MSTAR_CPU_PREFETCH_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_128K_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_128K_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_128K_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_128K_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_256K_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_256K_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_256K_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_256K_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_WRITE_BACK
#define ENABLE_MSTAR_TITANIA_L2_CACHE_WRITE_BACK 0
#define USE_MSTAR_TITANIA_L2_CACHE_WRITE_BACK(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_WRITE_BACK(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH
#define ENABLE_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH 0
#define USE_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES
#define ENABLE_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES 0
#define USE_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES(...)
#define SKIP_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES
#define ENABLE_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES 0
#define USE_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES(...)
#define SKIP_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_MEMORY_PREFETCH_ENABLE
#define ENABLE_MSTAR_MEMORY_PREFETCH_ENABLE 0
#define USE_MSTAR_MEMORY_PREFETCH_ENABLE(...)
#define SKIP_MSTAR_MEMORY_PREFETCH_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_FORCE_REQUEST_INTO_CACHE
#define ENABLE_MSTAR_FORCE_REQUEST_INTO_CACHE 0
#define USE_MSTAR_FORCE_REQUEST_INTO_CACHE(...)
#define SKIP_MSTAR_FORCE_REQUEST_INTO_CACHE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIU_HIGHWAY_ENABLE
#define ENABLE_MSTAR_MIU_HIGHWAY_ENABLE 0
#define USE_MSTAR_MIU_HIGHWAY_ENABLE(...)
#define SKIP_MSTAR_MIU_HIGHWAY_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_32BIT_RIU_MASK_ENABLE
#define ENABLE_MSTAR_32BIT_RIU_MASK_ENABLE 0
#define USE_MSTAR_32BIT_RIU_MASK_ENABLE(...)
#define SKIP_MSTAR_32BIT_RIU_MASK_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_TLB_SHARE_ENABLE
#define ENABLE_MSTAR_TLB_SHARE_ENABLE 0
#define USE_MSTAR_TLB_SHARE_ENABLE(...)
#define SKIP_MSTAR_TLB_SHARE_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MIU1_ENABLE
#define ENABLE_MSTAR_TITANIA_MIU1_ENABLE 0
#define USE_MSTAR_TITANIA_MIU1_ENABLE(...)
#define SKIP_MSTAR_TITANIA_MIU1_ENABLE(...) __VA_ARGS__

/*
 * General Configuration
 */
#define CONFIG_FEATURE_BUFFERS_USE_MALLOC 1
#define ENABLE_FEATURE_BUFFERS_USE_MALLOC 1
#define USE_FEATURE_BUFFERS_USE_MALLOC(...) __VA_ARGS__
#define SKIP_FEATURE_BUFFERS_USE_MALLOC(...)
#undef CONFIG_FEATURE_BUFFERS_GO_ON_STACK
#define ENABLE_FEATURE_BUFFERS_GO_ON_STACK 0
#define USE_FEATURE_BUFFERS_GO_ON_STACK(...)
#define SKIP_FEATURE_BUFFERS_GO_ON_STACK(...) __VA_ARGS__
#undef CONFIG_FEATURE_BUFFERS_GO_IN_BSS
#define ENABLE_FEATURE_BUFFERS_GO_IN_BSS 0
#define USE_FEATURE_BUFFERS_GO_IN_BSS(...)
#define SKIP_FEATURE_BUFFERS_GO_IN_BSS(...) __VA_ARGS__
#undef CONFIG_UART1_SEL
#define ENABLE_UART1_SEL 0
#define USE_UART1_SEL(...)
#define SKIP_UART1_SEL(...) __VA_ARGS__
#undef CONFIG_EMMC_BOOT
#define ENABLE_EMMC_BOOT 0
#define USE_EMMC_BOOT(...)
#define SKIP_EMMC_BOOT(...) __VA_ARGS__
#undef CONFIG_SBOOT_TO_KERNEL
#define ENABLE_SBOOT_TO_KERNEL 0
#define USE_SBOOT_TO_KERNEL(...)
#define SKIP_SBOOT_TO_KERNEL(...) __VA_ARGS__
#undef CONFIG_KERNEL_2_6_28_9
#define ENABLE_KERNEL_2_6_28_9 0
#define USE_KERNEL_2_6_28_9(...)
#define SKIP_KERNEL_2_6_28_9(...) __VA_ARGS__
#undef CONFIG_KERNEL_2_6_32_15
#define ENABLE_KERNEL_2_6_32_15 0
#define USE_KERNEL_2_6_32_15(...)
#define SKIP_KERNEL_2_6_32_15(...) __VA_ARGS__
#undef CONFIG_KERNEL_2_6_35_11
#define ENABLE_KERNEL_2_6_35_11 0
#define USE_KERNEL_2_6_35_11(...)
#define SKIP_KERNEL_2_6_35_11(...) __VA_ARGS__
#define CONFIG_SHOW_USAGE 1
#define ENABLE_SHOW_USAGE 1
#define USE_SHOW_USAGE(...) __VA_ARGS__
#define SKIP_SHOW_USAGE(...)
#define CONFIG_NON_OS 1
#define ENABLE_NON_OS 1
#define USE_NON_OS(...) __VA_ARGS__
#define SKIP_NON_OS(...)
#undef CONFIG_SBOOT_USE_BDMA_TO_CHECK_CRC
#define ENABLE_SBOOT_USE_BDMA_TO_CHECK_CRC 0
#define USE_SBOOT_USE_BDMA_TO_CHECK_CRC(...)
#define SKIP_SBOOT_USE_BDMA_TO_CHECK_CRC(...) __VA_ARGS__
#undef CONFIG_SECURE_BOOT
#define ENABLE_SECURE_BOOT 0
#define USE_SECURE_BOOT(...)
#define SKIP_SECURE_BOOT(...) __VA_ARGS__
#undef CONFIG_COMPRESSED_UBOOT
#define ENABLE_COMPRESSED_UBOOT 0
#define USE_COMPRESSED_UBOOT(...)
#define SKIP_COMPRESSED_UBOOT(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_PM
#define ENABLE_MSTAR_MARIA10_PM 0
#define USE_MSTAR_MARIA10_PM(...)
#define SKIP_MSTAR_MARIA10_PM(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_PM
#define ENABLE_MSTAR_MACAW12_PM 0
#define USE_MSTAR_MACAW12_PM(...)
#define SKIP_MSTAR_MACAW12_PM(...) __VA_ARGS__

/*
 * Build Options
 */
#define CONFIG_CROSS_COMPILER_PREFIX "aeon-"
#define ENABLE_CROSS_COMPILER_PREFIX 1
#define USE_CROSS_COMPILER_PREFIX(...) __VA_ARGS__
#define SKIP_CROSS_COMPILER_PREFIX(...)
#define CONFIG_EXTRA_CFLAGS "-march=aeonR2 -EL"
#define ENABLE_EXTRA_CFLAGS 1
#define USE_EXTRA_CFLAGS(...) __VA_ARGS__
#define SKIP_EXTRA_CFLAGS(...)
#define CONFIG_EXTRA_AFLAGS ""
#define ENABLE_EXTRA_AFLAGS 1
#define USE_EXTRA_AFLAGS(...) __VA_ARGS__
#define SKIP_EXTRA_AFLAGS(...)

/*
 * Debugging Options
 */
#undef CONFIG_DEBUG
#define ENABLE_DEBUG 0
#define USE_DEBUG(...)
#define SKIP_DEBUG(...) __VA_ARGS__
#undef CONFIG_DEBUG_PESSIMIZE
#define ENABLE_DEBUG_PESSIMIZE 0
#define USE_DEBUG_PESSIMIZE(...)
#define SKIP_DEBUG_PESSIMIZE(...) __VA_ARGS__
#undef CONFIG_WERROR
#define ENABLE_WERROR 0
#define USE_WERROR(...)
#define SKIP_WERROR(...) __VA_ARGS__
#undef CONFIG_EARLY_DISABLE_UART
#define ENABLE_EARLY_DISABLE_UART 0
#define USE_EARLY_DISABLE_UART(...)
#define SKIP_EARLY_DISABLE_UART(...) __VA_ARGS__

/*
 * Installation Options
 */
#define CONFIG_PREFIX "./_install"
#define ENABLE_PREFIX 1
#define USE_PREFIX(...) __VA_ARGS__
#define SKIP_PREFIX(...)

/*
 * Module Options
 */
#undef CONFIG_ANDROID_SUPPORT
#define ENABLE_ANDROID_SUPPORT 0
#define USE_ANDROID_SUPPORT(...)
#define SKIP_ANDROID_SUPPORT(...) __VA_ARGS__
#undef CONFIG_ANDROID_BOOT
#define ENABLE_ANDROID_BOOT 0
#define USE_ANDROID_BOOT(...)
#define SKIP_ANDROID_BOOT(...) __VA_ARGS__
#undef CONFIG_USB
#define ENABLE_USB 0
#define USE_USB(...)
#define SKIP_USB(...) __VA_ARGS__
#undef CONFIG_USB_LAN
#define ENABLE_USB_LAN 0
#define USE_USB_LAN(...)
#define SKIP_USB_LAN(...) __VA_ARGS__
#define CONFIG_FLASH_TYPE 1
#define ENABLE_FLASH_TYPE 1
#define USE_FLASH_TYPE(...) __VA_ARGS__
#define SKIP_FLASH_TYPE(...)
#define CONFIG_NAND_FLASH 1
#define ENABLE_NAND_FLASH 1
#define USE_NAND_FLASH(...) __VA_ARGS__
#define SKIP_NAND_FLASH(...)
#undef CONFIG_BFN_WRITE_NAND
#define ENABLE_BFN_WRITE_NAND 0
#define USE_BFN_WRITE_NAND(...)
#define SKIP_BFN_WRITE_NAND(...) __VA_ARGS__
#undef CONFIG_BOOT_FROM_NAND
#define ENABLE_BOOT_FROM_NAND 0
#define USE_BOOT_FROM_NAND(...)
#define SKIP_BOOT_FROM_NAND(...) __VA_ARGS__
#undef CONFIG_MMC
#define ENABLE_MMC 0
#define USE_MMC(...)
#define SKIP_MMC(...) __VA_ARGS__
#undef CONFIG_BOOT_FROM_EMMC
#define ENABLE_BOOT_FROM_EMMC 0
#define USE_BOOT_FROM_EMMC(...)
#define SKIP_BOOT_FROM_EMMC(...) __VA_ARGS__
#undef CONFIG_SPI
#define ENABLE_SPI 0
#define USE_SPI(...)
#define SKIP_SPI(...) __VA_ARGS__
#undef CONFIG_FLASH
#define ENABLE_FLASH 0
#define USE_FLASH(...)
#define SKIP_FLASH(...) __VA_ARGS__
#define CONFIG_UBI 1
#define ENABLE_UBI 1
#define USE_UBI(...) __VA_ARGS__
#define SKIP_UBI(...)
#undef CONFIG_UBI_MLC_BACKUP_LSB
#define ENABLE_UBI_MLC_BACKUP_LSB 0
#define USE_UBI_MLC_BACKUP_LSB(...)
#define SKIP_UBI_MLC_BACKUP_LSB(...) __VA_ARGS__
#undef CONFIG_UBI_ENHANCE_INIT
#define ENABLE_UBI_ENHANCE_INIT 0
#define USE_UBI_ENHANCE_INIT(...)
#define SKIP_UBI_ENHANCE_INIT(...) __VA_ARGS__
#define CONFIG_FILE_SYSTEM 1
#define ENABLE_FILE_SYSTEM 1
#define USE_FILE_SYSTEM(...) __VA_ARGS__
#define SKIP_FILE_SYSTEM(...)
#undef CONFIG_FAT
#define ENABLE_FAT 0
#define USE_FAT(...)
#define SKIP_FAT(...) __VA_ARGS__
#define CONFIG_UBI_FS 1
#define ENABLE_UBI_FS 1
#define USE_UBI_FS(...) __VA_ARGS__
#define SKIP_UBI_FS(...)
#define CONFIG_JFFS2 1
#define ENABLE_JFFS2 1
#define USE_JFFS2(...) __VA_ARGS__
#define SKIP_JFFS2(...)
#undef CONFIG_CMD_EXT2
#define ENABLE_CMD_EXT2 0
#define USE_CMD_EXT2(...)
#define SKIP_CMD_EXT2(...) __VA_ARGS__
#undef CONFIG_CMD_EXT4
#define ENABLE_CMD_EXT4 0
#define USE_CMD_EXT4(...)
#define SKIP_CMD_EXT4(...) __VA_ARGS__
#undef CONFIG_CMD_EXT4_WRITE
#define ENABLE_CMD_EXT4_WRITE 0
#define USE_CMD_EXT4_WRITE(...)
#define SKIP_CMD_EXT4_WRITE(...) __VA_ARGS__
#undef CONFIG_KEYPAD
#define ENABLE_KEYPAD 0
#define USE_KEYPAD(...)
#define SKIP_KEYPAD(...) __VA_ARGS__
#undef CONFIG_BOOT_KEYPAD
#define ENABLE_BOOT_KEYPAD 0
#define USE_BOOT_KEYPAD(...)
#define SKIP_BOOT_KEYPAD(...) __VA_ARGS__
#undef CONFIG_IR
#define ENABLE_IR 0
#define USE_IR(...)
#define SKIP_IR(...) __VA_ARGS__
#undef CONFIG_BOOT_IR
#define ENABLE_BOOT_IR 0
#define USE_BOOT_IR(...)
#define SKIP_BOOT_IR(...) __VA_ARGS__
#undef CONFIG_SECURITY_BOOT
#define ENABLE_SECURITY_BOOT 0
#define USE_SECURITY_BOOT(...)
#define SKIP_SECURITY_BOOT(...) __VA_ARGS__
#undef CONFIG_SECURE_AESDMA
#define ENABLE_SECURE_AESDMA 0
#define USE_SECURE_AESDMA(...)
#define SKIP_SECURE_AESDMA(...) __VA_ARGS__
#undef CONFIG_SECURE_PARTIAL_AUTHENTICATION
#define ENABLE_SECURE_PARTIAL_AUTHENTICATION 0
#define USE_SECURE_PARTIAL_AUTHENTICATION(...)
#define SKIP_SECURE_PARTIAL_AUTHENTICATION(...) __VA_ARGS__
#undef CONFIG_SECURE_USB_UPGRADE
#define ENABLE_SECURE_USB_UPGRADE 0
#define USE_SECURE_USB_UPGRADE(...)
#define SKIP_SECURE_USB_UPGRADE(...) __VA_ARGS__
#undef CONFIG_SECURE_DEBUG_MESSAGE
#define ENABLE_SECURE_DEBUG_MESSAGE 0
#define USE_SECURE_DEBUG_MESSAGE(...)
#define SKIP_SECURE_DEBUG_MESSAGE(...) __VA_ARGS__
#undef CONFIG_SECURE_SPI_PROTECT
#define ENABLE_SECURE_SPI_PROTECT 0
#define USE_SECURE_SPI_PROTECT(...)
#define SKIP_SECURE_SPI_PROTECT(...) __VA_ARGS__
#undef CONFIG_BOOTING_ACTIVE_SPI_PROTECT
#define ENABLE_BOOTING_ACTIVE_SPI_PROTECT 0
#define USE_BOOTING_ACTIVE_SPI_PROTECT(...)
#define SKIP_BOOTING_ACTIVE_SPI_PROTECT(...) __VA_ARGS__
#undef CONFIG_SECURE_SPI_PARTIAL_PROTECT
#define ENABLE_SECURE_SPI_PARTIAL_PROTECT 0
#define USE_SECURE_SPI_PARTIAL_PROTECT(...)
#define SKIP_SECURE_SPI_PARTIAL_PROTECT(...) __VA_ARGS__
#undef CONFIG_SECURE_SPI_FULL_PROTECT
#define ENABLE_SECURE_SPI_FULL_PROTECT 0
#define USE_SECURE_SPI_FULL_PROTECT(...)
#define SKIP_SECURE_SPI_FULL_PROTECT(...) __VA_ARGS__
#define CONFIG_SECURE_SPI_PROTECT_SPACE 0x
#define ENABLE_SECURE_SPI_PROTECT_SPACE 1
#define USE_SECURE_SPI_PROTECT_SPACE(...) __VA_ARGS__
#define SKIP_SECURE_SPI_PROTECT_SPACE(...)
#define CONFIG_SECURE_SPI_NON_PROTECT_SPACE 0x
#define ENABLE_SECURE_SPI_NON_PROTECT_SPACE 1
#define USE_SECURE_SPI_NON_PROTECT_SPACE(...) __VA_ARGS__
#define SKIP_SECURE_SPI_NON_PROTECT_SPACE(...)
#undef CONFIG_LZO
#define ENABLE_LZO 0
#define USE_LZO(...)
#define SKIP_LZO(...) __VA_ARGS__
#define CONFIG_UNLZO_DST_ADDR 0x
#define ENABLE_UNLZO_DST_ADDR 1
#define USE_UNLZO_DST_ADDR(...) __VA_ARGS__
#define SKIP_UNLZO_DST_ADDR(...)
#undef CONFIG_DISPLAY_LOGO
#define ENABLE_DISPLAY_LOGO 0
#define USE_DISPLAY_LOGO(...)
#define SKIP_DISPLAY_LOGO(...) __VA_ARGS__
#undef CONFIG_LOGO_STORE_IN_SPI_FLASH
#define ENABLE_LOGO_STORE_IN_SPI_FLASH 0
#define USE_LOGO_STORE_IN_SPI_FLASH(...)
#define SKIP_LOGO_STORE_IN_SPI_FLASH(...) __VA_ARGS__
#undef CONFIG_LOGO_STORE_IN_NAND_FLASH
#define ENABLE_LOGO_STORE_IN_NAND_FLASH 0
#define USE_LOGO_STORE_IN_NAND_FLASH(...)
#define SKIP_LOGO_STORE_IN_NAND_FLASH(...) __VA_ARGS__
#undef CONFIG_LOGO_STORE_IN_EMMC_FLASH
#define ENABLE_LOGO_STORE_IN_EMMC_FLASH 0
#define USE_LOGO_STORE_IN_EMMC_FLASH(...)
#define SKIP_LOGO_STORE_IN_EMMC_FLASH(...) __VA_ARGS__
#undef CONFIG_GOP_OP_PATH
#define ENABLE_GOP_OP_PATH 0
#define USE_GOP_OP_PATH(...)
#define SKIP_GOP_OP_PATH(...) __VA_ARGS__
#undef CONFIG_GOP_MIXER2OP_PATH
#define ENABLE_GOP_MIXER2OP_PATH 0
#define USE_GOP_MIXER2OP_PATH(...)
#define SKIP_GOP_MIXER2OP_PATH(...) __VA_ARGS__
#define CONFIG_DISPLAY_LOGO_SPACE 0x
#define ENABLE_DISPLAY_LOGO_SPACE 1
#define USE_DISPLAY_LOGO_SPACE(...) __VA_ARGS__
#define SKIP_DISPLAY_LOGO_SPACE(...)
#undef CONFIG_DISPLAY_OSD
#define ENABLE_DISPLAY_OSD 0
#define USE_DISPLAY_OSD(...)
#define SKIP_DISPLAY_OSD(...) __VA_ARGS__
#undef CONFIG_BOOTLOGO_OUT_CVBS
#define ENABLE_BOOTLOGO_OUT_CVBS 0
#define USE_BOOTLOGO_OUT_CVBS(...)
#define SKIP_BOOTLOGO_OUT_CVBS(...) __VA_ARGS__
#undef CONFIG_BOOTLOGO_OUT_SCART_HD_DAC
#define ENABLE_BOOTLOGO_OUT_SCART_HD_DAC 0
#define USE_BOOTLOGO_OUT_SCART_HD_DAC(...)
#define SKIP_BOOTLOGO_OUT_SCART_HD_DAC(...) __VA_ARGS__
#undef CONFIG_BOOTLOGO_OUT_SCART_SD_DAC
#define ENABLE_BOOTLOGO_OUT_SCART_SD_DAC 0
#define USE_BOOTLOGO_OUT_SCART_SD_DAC(...)
#define SKIP_BOOTLOGO_OUT_SCART_SD_DAC(...) __VA_ARGS__
#undef CONFIG_POWER_MUSIC
#define ENABLE_POWER_MUSIC 0
#define USE_POWER_MUSIC(...)
#define SKIP_POWER_MUSIC(...) __VA_ARGS__
#undef CONFIG_DIGITAL_TI5711
#define ENABLE_DIGITAL_TI5711 0
#define USE_DIGITAL_TI5711(...)
#define SKIP_DIGITAL_TI5711(...) __VA_ARGS__
#undef CONFIG_DIGITAL_TI5707
#define ENABLE_DIGITAL_TI5707 0
#define USE_DIGITAL_TI5707(...)
#define SKIP_DIGITAL_TI5707(...) __VA_ARGS__
#undef CONFIG_DIGITAL_TI5708
#define ENABLE_DIGITAL_TI5708 0
#define USE_DIGITAL_TI5708(...)
#define SKIP_DIGITAL_TI5708(...) __VA_ARGS__
#undef CONFIG_DIGITAL_STA333
#define ENABLE_DIGITAL_STA333 0
#define USE_DIGITAL_STA333(...)
#define SKIP_DIGITAL_STA333(...) __VA_ARGS__
#undef CONFIG_SIM_Amplifier
#define ENABLE_SIM_Amplifier 0
#define USE_SIM_Amplifier(...)
#define SKIP_SIM_Amplifier(...) __VA_ARGS__
#undef CONFIG_FRONT_END
#define ENABLE_FRONT_END 0
#define USE_FRONT_END(...)
#define SKIP_FRONT_END(...) __VA_ARGS__
#undef CONFIG_MSTAR_TUNER_NUTUNE_FT2125
#define ENABLE_MSTAR_TUNER_NUTUNE_FT2125 0
#define USE_MSTAR_TUNER_NUTUNE_FT2125(...)
#define SKIP_MSTAR_TUNER_NUTUNE_FT2125(...) __VA_ARGS__
#undef CONFIG_MSTAR_TUNER_NUTUNE_FJ2207
#define ENABLE_MSTAR_TUNER_NUTUNE_FJ2207 0
#define USE_MSTAR_TUNER_NUTUNE_FJ2207(...)
#define SKIP_MSTAR_TUNER_NUTUNE_FJ2207(...) __VA_ARGS__
#undef CONFIG_MSTAR_TUNER_NXP_TD1611ALF
#define ENABLE_MSTAR_TUNER_NXP_TD1611ALF 0
#define USE_MSTAR_TUNER_NXP_TD1611ALF(...)
#define SKIP_MSTAR_TUNER_NXP_TD1611ALF(...) __VA_ARGS__
#undef CONFIG_MSTAR_MSB123x_DEMOD
#define ENABLE_MSTAR_MSB123x_DEMOD 0
#define USE_MSTAR_MSB123x_DEMOD(...)
#define SKIP_MSTAR_MSB123x_DEMOD(...) __VA_ARGS__
#undef CONFIG_MSTAR_MSB122x_DEMOD
#define ENABLE_MSTAR_MSB122x_DEMOD 0
#define USE_MSTAR_MSB122x_DEMOD(...)
#define SKIP_MSTAR_MSB122x_DEMOD(...) __VA_ARGS__
#undef CONFIG_DEMUX
#define ENABLE_DEMUX 0
#define USE_DEMUX(...)
#define SKIP_DEMUX(...) __VA_ARGS__
#define CONFIG_NET 1
#define ENABLE_NET 1
#define USE_NET(...) __VA_ARGS__
#define SKIP_NET(...)
#undef CONFIG_NETUPDATE
#define ENABLE_NETUPDATE 0
#define USE_NETUPDATE(...)
#define SKIP_NETUPDATE(...) __VA_ARGS__
#define CONFIG_PHY_SELECTION 1
#define ENABLE_PHY_SELECTION 1
#define USE_PHY_SELECTION(...) __VA_ARGS__
#define SKIP_PHY_SELECTION(...)
#undef CONFIG_ALBANY
#define ENABLE_ALBANY 0
#define USE_ALBANY(...)
#define SKIP_ALBANY(...) __VA_ARGS__
#undef CONFIG_ETHERNET_ALBANY
#define ENABLE_ETHERNET_ALBANY 0
#define USE_ETHERNET_ALBANY(...)
#define SKIP_ETHERNET_ALBANY(...) __VA_ARGS__
#undef CONFIG_OAD
#define ENABLE_OAD 0
#define USE_OAD(...)
#define SKIP_OAD(...) __VA_ARGS__
#undef CONFIG_OBAMA_OAD
#define ENABLE_OBAMA_OAD 0
#define USE_OBAMA_OAD(...)
#define SKIP_OBAMA_OAD(...) __VA_ARGS__
#undef CONFIG_SUPERNOVA_OAD
#define ENABLE_SUPERNOVA_OAD 0
#define USE_SUPERNOVA_OAD(...)
#define SKIP_SUPERNOVA_OAD(...) __VA_ARGS__
#undef CONFIG_OAD_IN_MBOOT
#define ENABLE_OAD_IN_MBOOT 0
#define USE_OAD_IN_MBOOT(...)
#define SKIP_OAD_IN_MBOOT(...) __VA_ARGS__
#define CONFIG_MTD_NAND_BBT 1
#define ENABLE_MTD_NAND_BBT 1
#define USE_MTD_NAND_BBT(...) __VA_ARGS__
#define SKIP_MTD_NAND_BBT(...)
#undef CONFIG_URSA_6M30
#define ENABLE_URSA_6M30 0
#define USE_URSA_6M30(...)
#define SKIP_URSA_6M30(...) __VA_ARGS__
#undef CONFIG_PANEL_INIT
#define ENABLE_PANEL_INIT 0
#define USE_PANEL_INIT(...)
#define SKIP_PANEL_INIT(...) __VA_ARGS__
#undef CONFIG_MSTARI2C
#define ENABLE_MSTARI2C 0
#define USE_MSTARI2C(...)
#define SKIP_MSTARI2C(...) __VA_ARGS__
#undef CONFIG_EEPROM
#define ENABLE_EEPROM 0
#define USE_EEPROM(...)
#define SKIP_EEPROM(...) __VA_ARGS__
#undef CONFIG_STANDBY
#define ENABLE_STANDBY 0
#define USE_STANDBY(...)
#define SKIP_STANDBY(...) __VA_ARGS__
#define CONFIG_VFS 1
#define ENABLE_VFS 1
#define USE_VFS(...) __VA_ARGS__
#define SKIP_VFS(...)
#undef CONFIG_MICOM
#define ENABLE_MICOM 0
#define USE_MICOM(...)
#define SKIP_MICOM(...) __VA_ARGS__
#undef CONFIG_WDT
#define ENABLE_WDT 0
#define USE_WDT(...)
#define SKIP_WDT(...) __VA_ARGS__
#undef CONFIG_BACKUP_PARTITION
#define ENABLE_BACKUP_PARTITION 0
#define USE_BACKUP_PARTITION(...)
#define SKIP_BACKUP_PARTITION(...) __VA_ARGS__
#undef CONFIG_ENV_IN_SERIAL
#define ENABLE_ENV_IN_SERIAL 0
#define USE_ENV_IN_SERIAL(...)
#define SKIP_ENV_IN_SERIAL(...) __VA_ARGS__
#undef CONFIG_ENV_IN_MMC
#define ENABLE_ENV_IN_MMC 0
#define USE_ENV_IN_MMC(...)
#define SKIP_ENV_IN_MMC(...) __VA_ARGS__
#define CONFIG_ENV_IN_NAND 1
#define ENABLE_ENV_IN_NAND 1
#define USE_ENV_IN_NAND(...) __VA_ARGS__
#define SKIP_ENV_IN_NAND(...)
#undef CONFIG_ENV_IN_UBI
#define ENABLE_ENV_IN_UBI 0
#define USE_ENV_IN_UBI(...)
#define SKIP_ENV_IN_UBI(...) __VA_ARGS__
#undef CONFIG_ENV_IN_SERIAL_512K
#define ENABLE_ENV_IN_SERIAL_512K 0
#define USE_ENV_IN_SERIAL_512K(...)
#define SKIP_ENV_IN_SERIAL_512K(...) __VA_ARGS__
#undef CONFIG_ENV_IN_ERR
#define ENABLE_ENV_IN_ERR 0
#define USE_ENV_IN_ERR(...)
#define SKIP_ENV_IN_ERR(...) __VA_ARGS__
#undef CONFIG_INFO_IN_UBI_FILE
#define ENABLE_INFO_IN_UBI_FILE 0
#define USE_INFO_IN_UBI_FILE(...)
#define SKIP_INFO_IN_UBI_FILE(...) __VA_ARGS__
#undef CONFIG_INFO_IN_SERIAL_ENV
#define ENABLE_INFO_IN_SERIAL_ENV 0
#define USE_INFO_IN_SERIAL_ENV(...)
#define SKIP_INFO_IN_SERIAL_ENV(...) __VA_ARGS__
#undef CONFIG_INFO_IN_MMC_ENV
#define ENABLE_INFO_IN_MMC_ENV 0
#define USE_INFO_IN_MMC_ENV(...)
#define SKIP_INFO_IN_MMC_ENV(...) __VA_ARGS__
#undef CONFIG_INFO_IN_ERR
#define ENABLE_INFO_IN_ERR 0
#define USE_INFO_IN_ERR(...)
#define SKIP_INFO_IN_ERR(...) __VA_ARGS__
