#ifndef _BBCONFIGOPTS_H
#define _BBCONFIGOPTS_H
/*
 * sboot configuration settings.
 *
 * Licensed under GPLv2 or later, see file LICENSE in this tarball for details.
 *
 * This file is generated automatically by scripts/mkconfigs.
 * Do not edit.
 *
 */
static const char *const bbconfig_config =
"CONFIG_HAVE_DOT_CONFIG=y\n"
"CONFIG_MSTAR_MST9U=y\n"
"# CONFIG_MSTAR_AMBER7 is not set\n"
"# CONFIG_MSTAR_MACAW12 is not set\n"
"CONFIG_MSTAR_CHIP_NAME=\"MST9U\"\n"
"# CONFIG_MCU_MIPS32 is not set\n"
"# CONFIG_MCU_ARM is not set\n"
"CONFIG_MCU_AEONR2=y\n"
"CONFIG_BOOTING_FROM_EXT_SPI_WITH_CPU=y\n"
"# CONFIG_BOOTING_FROM_EXT_SPI_WITH_PM51 is not set\n"
"# CONFIG_BOOTING_FROM_OTP_WITH_PM51 is not set\n"
"# CONFIG_CPU_345MHZ is not set\n"
"CONFIG_CPU_320MHZ=y\n"
"# CONFIG_CPU_288MHZ is not set\n"
"# CONFIG_CPU_240MHZ is not set\n"
"# CONFIG_CPU_216MHZ is not set\n"
"# CONFIG_CPU_192MHZ is not set\n"
"# CONFIG_CPU_144MHZ is not set\n"
"# CONFIG_CPU_108MHZ is not set\n"
"# CONFIG_MSTAR_MANUAL is not set\n"
"CONFIG_MSTAR_OTHERS=0\n"
"# CONFIG_MSTAR_BD_FPGA is not set\n"
"CONFIG_MSTAR_MST9U_BD_MSTxxxA_DxxA_S=y\n"
"# CONFIG_PNL_FULLHD_SEC_LE32A is not set\n"
"# CONFIG_PNL_SXGA_AU17_EN05 is not set\n"
"CONFIG_PNL_WXGA_AU20_T200XW02=y\n"
"# CONFIG_PNL_WXGA_PLUS_CMO190_M190A1 is not set\n"
"# CONFIG_PNL_WSXGA_AU22_M201EW01 is not set\n"
"# CONFIG_PNL_FULLHD_CMO216_H1L01 is not set\n"
"# CONFIG_PANEL_RES_FULL_HD is not set\n"
"# CONFIG_PNL_WUXGA_CMO260_J2 is not set\n"
"# CONFIG_MFC120_FULLHD_CMO216_H1L01 is not set\n"
"# CONFIG_MFC60_FULLHD_CMO216_H1L01 is not set\n"
"# CONFIG_PNL_FULLHD_TCON is not set\n"
"# CONFIG_PNL_DACOUT_576I is not set\n"
"# CONFIG_PNL_DACOUT_576P is not set\n"
"# CONFIG_PNL_DACOUT_720P_50 is not set\n"
"# CONFIG_PNL_DACOUT_1080I_50 is not set\n"
"# CONFIG_PNL_DACOUT_1080P_50 is not set\n"
"# CONFIG_PNL_DACOUT_480I is not set\n"
"# CONFIG_PNL_DACOUT_480P is not set\n"
"# CONFIG_PNL_DACOUT_720P_60 is not set\n"
"# CONFIG_PNL_DACOUT_1080I_60 is not set\n"
"# CONFIG_PNL_DACOUT_1080P_60 is not set\n"
"# CONFIG_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT is not set\n"
"CONFIG_MSTAR_MST9U_MMAP_512MB=y\n"
"# CONFIG_MSTAR_MST9U_MMAP_256MB is not set\n"
"CONFIG_MEM2133MHz=y\n"
"# CONFIG_MEM1866MHz is not set\n"
"# CONFIG_MEM1333MHz is not set\n"
"# CONFIG_MEM1600MHz is not set\n"
"# CONFIG_MEM1300MHz is not set\n"
"# CONFIG_MEM1066MHz is not set\n"
"# CONFIG_DDR3_16BIT_MODE is not set\n"
"# CONFIG_DDR3_8BIT_MODE is not set\n"
"# CONFIG_MIU0_DRAM_NONE is not set\n"
"# CONFIG_MIU0_DDR3_1666 is not set\n"
"# CONFIG_MIU0_DDR3_1333 is not set\n"
"# CONFIG_MIU0_DDR3_1066 is not set\n"
"# CONFIG_MIU0_DDR2_1066 is not set\n"
"# CONFIG_MIU0_DDR2_800 is not set\n"
"# CONFIG_MIU1_DRAM_NONE is not set\n"
"# CONFIG_MIU1_DDR3_1666 is not set\n"
"# CONFIG_MIU1_DDR3_1333 is not set\n"
"# CONFIG_MIU1_DDR3_1066 is not set\n"
"# CONFIG_MIU1_DDR2_1066 is not set\n"
"# CONFIG_MIU1_DDR2_800 is not set\n"
"# CONFIG_ENABLE_MIU_SWAP is not set\n"
"# CONFIG_BIST_0x0401_UNITS is not set\n"
"CONFIG_BIST_0x1001_UNITS=y\n"
"# CONFIG_BIST_0x8001_UNITS is not set\n"
"CONFIG_BOOTRAM_LOADADDR=0x01000000\n"
"CONFIG_UBOOT_LOADADDR=0x41200000\n"
"CONFIG_DRAM_SIZE_MB_RELOCATE=256\n"
"# CONFIG_MSTAR_STR_ENABLE is not set\n"
"CONFIG_PM_DRAM_ADDRESS=\n"
"CONFIG_CUSTOMER_KEY_BANK_DRAM_ADDRESS=\n"
"CONFIG_SECURE_INFO_DRAM_ADDRESS=\n"
"# CONFIG_MSTAR_MOBF_ENABLE is not set\n"
"# CONFIG_MSTAR_ASIC_EMULATION_ENABLE is not set\n"
"# CONFIG_MSTAR_MIPS_SINGLE_CORE is not set\n"
"# CONFIG_MSTAR_MIPS_DUAL_CORE is not set\n"
"# CONFIG_MSTAR_MIPS_SINGLE_VPE_PER_CORE is not set\n"
"# CONFIG_MSTAR_MIPS_DUAL_VPE_PER_CORE is not set\n"
"# CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1 is not set\n"
"# CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2 is not set\n"
"# CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3 is not set\n"
"# CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4 is not set\n"
"# CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5 is not set\n"
"# CONFIG_MSTAR_L2_CACHE_ENABLE is not set\n"
"# CONFIG_MSTAR_CPU_PREFETCH_ENABLE is not set\n"
"# CONFIG_MSTAR_TITANIA_L2_CACHE_128K_BYTES is not set\n"
"# CONFIG_MSTAR_TITANIA_L2_CACHE_256K_BYTES is not set\n"
"# CONFIG_MSTAR_TITANIA_L2_CACHE_WRITE_BACK is not set\n"
"# CONFIG_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH is not set\n"
"# CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES is not set\n"
"# CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES is not set\n"
"# CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES is not set\n"
"# CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES is not set\n"
"# CONFIG_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES is not set\n"
"# CONFIG_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES is not set\n"
"# CONFIG_MSTAR_MEMORY_PREFETCH_ENABLE is not set\n"
"# CONFIG_MSTAR_FORCE_REQUEST_INTO_CACHE is not set\n"
"# CONFIG_MSTAR_MIU_HIGHWAY_ENABLE is not set\n"
"# CONFIG_MSTAR_32BIT_RIU_MASK_ENABLE is not set\n"
"# CONFIG_MSTAR_TLB_SHARE_ENABLE is not set\n"
"# CONFIG_MSTAR_TITANIA_MIU1_ENABLE is not set\n"
"CONFIG_FEATURE_BUFFERS_USE_MALLOC=y\n"
"# CONFIG_FEATURE_BUFFERS_GO_ON_STACK is not set\n"
"# CONFIG_FEATURE_BUFFERS_GO_IN_BSS is not set\n"
"# CONFIG_UART1_SEL is not set\n"
"# CONFIG_EMMC_BOOT is not set\n"
"# CONFIG_SBOOT_TO_KERNEL is not set\n"
"# CONFIG_KERNEL_2_6_28_9 is not set\n"
"# CONFIG_KERNEL_2_6_32_15 is not set\n"
"# CONFIG_KERNEL_2_6_35_11 is not set\n"
"CONFIG_SHOW_USAGE=y\n"
"CONFIG_NON_OS=y\n"
"# CONFIG_SBOOT_USE_BDMA_TO_CHECK_CRC is not set\n"
"# CONFIG_SECURE_BOOT is not set\n"
"# CONFIG_COMPRESSED_UBOOT is not set\n"
"# CONFIG_MSTAR_MARIA10_PM is not set\n"
"# CONFIG_MSTAR_MACAW12_PM is not set\n"
"CONFIG_CROSS_COMPILER_PREFIX=\"aeon-\"\n"
"CONFIG_EXTRA_CFLAGS=\"-march=aeonR2 -EL\"\n"
"CONFIG_EXTRA_AFLAGS=\"\"\n"
"# CONFIG_DEBUG is not set\n"
"# CONFIG_DEBUG_PESSIMIZE is not set\n"
"# CONFIG_WERROR is not set\n"
"# CONFIG_EARLY_DISABLE_UART is not set\n"
"CONFIG_PREFIX=\"./_install\"\n"
"# CONFIG_ANDROID_SUPPORT is not set\n"
"# CONFIG_ANDROID_BOOT is not set\n"
"# CONFIG_USB is not set\n"
"# CONFIG_USB_LAN is not set\n"
"CONFIG_FLASH_TYPE=y\n"
"CONFIG_NAND_FLASH=y\n"
"# CONFIG_BFN_WRITE_NAND is not set\n"
"# CONFIG_BOOT_FROM_NAND is not set\n"
"# CONFIG_MMC is not set\n"
"# CONFIG_BOOT_FROM_EMMC is not set\n"
"# CONFIG_SPI is not set\n"
"# CONFIG_FLASH is not set\n"
"CONFIG_UBI=y\n"
"# CONFIG_UBI_MLC_BACKUP_LSB is not set\n"
"# CONFIG_UBI_ENHANCE_INIT is not set\n"
"CONFIG_FILE_SYSTEM=y\n"
"# CONFIG_FAT is not set\n"
"CONFIG_UBI_FS=y\n"
"CONFIG_JFFS2=y\n"
"# CONFIG_CMD_EXT2 is not set\n"
"# CONFIG_CMD_EXT4 is not set\n"
"# CONFIG_CMD_EXT4_WRITE is not set\n"
"# CONFIG_KEYPAD is not set\n"
"# CONFIG_BOOT_KEYPAD is not set\n"
"# CONFIG_IR is not set\n"
"# CONFIG_BOOT_IR is not set\n"
"# CONFIG_SECURITY_BOOT is not set\n"
"# CONFIG_SECURE_AESDMA is not set\n"
"# CONFIG_SECURE_PARTIAL_AUTHENTICATION is not set\n"
"# CONFIG_SECURE_USB_UPGRADE is not set\n"
"# CONFIG_SECURE_DEBUG_MESSAGE is not set\n"
"# CONFIG_SECURE_SPI_PROTECT is not set\n"
"# CONFIG_BOOTING_ACTIVE_SPI_PROTECT is not set\n"
"# CONFIG_SECURE_SPI_PARTIAL_PROTECT is not set\n"
"# CONFIG_SECURE_SPI_FULL_PROTECT is not set\n"
"CONFIG_SECURE_SPI_PROTECT_SPACE=\n"
"CONFIG_SECURE_SPI_NON_PROTECT_SPACE=\n"
"# CONFIG_LZO is not set\n"
"CONFIG_UNLZO_DST_ADDR=\n"
"# CONFIG_DISPLAY_LOGO is not set\n"
"# CONFIG_LOGO_STORE_IN_SPI_FLASH is not set\n"
"# CONFIG_LOGO_STORE_IN_NAND_FLASH is not set\n"
"# CONFIG_LOGO_STORE_IN_EMMC_FLASH is not set\n"
"# CONFIG_GOP_OP_PATH is not set\n"
"# CONFIG_GOP_MIXER2OP_PATH is not set\n"
"CONFIG_DISPLAY_LOGO_SPACE=\n"
"# CONFIG_DISPLAY_OSD is not set\n"
"# CONFIG_BOOTLOGO_OUT_CVBS is not set\n"
"# CONFIG_BOOTLOGO_OUT_SCART_HD_DAC is not set\n"
"# CONFIG_BOOTLOGO_OUT_SCART_SD_DAC is not set\n"
"# CONFIG_POWER_MUSIC is not set\n"
"# CONFIG_DIGITAL_TI5711 is not set\n"
"# CONFIG_DIGITAL_TI5707 is not set\n"
"# CONFIG_DIGITAL_TI5708 is not set\n"
"# CONFIG_DIGITAL_STA333 is not set\n"
"# CONFIG_SIM_Amplifier is not set\n"
"# CONFIG_FRONT_END is not set\n"
"# CONFIG_MSTAR_TUNER_NUTUNE_FT2125 is not set\n"
"# CONFIG_MSTAR_TUNER_NUTUNE_FJ2207 is not set\n"
"# CONFIG_MSTAR_TUNER_NXP_TD1611ALF is not set\n"
"# CONFIG_MSTAR_MSB123x_DEMOD is not set\n"
"# CONFIG_MSTAR_MSB122x_DEMOD is not set\n"
"# CONFIG_DEMUX is not set\n"
"CONFIG_NET=y\n"
"# CONFIG_NETUPDATE is not set\n"
"CONFIG_PHY_SELECTION=y\n"
"# CONFIG_ALBANY is not set\n"
"# CONFIG_ETHERNET_ALBANY is not set\n"
"# CONFIG_OAD is not set\n"
"# CONFIG_OBAMA_OAD is not set\n"
"# CONFIG_SUPERNOVA_OAD is not set\n"
"# CONFIG_OAD_IN_MBOOT is not set\n"
"CONFIG_MTD_NAND_BBT=y\n"
"# CONFIG_URSA_6M30 is not set\n"
"# CONFIG_PANEL_INIT is not set\n"
"# CONFIG_MSTARI2C is not set\n"
"# CONFIG_EEPROM is not set\n"
"# CONFIG_STANDBY is not set\n"
"CONFIG_VFS=y\n"
"# CONFIG_MICOM is not set\n"
"# CONFIG_WDT is not set\n"
"# CONFIG_BACKUP_PARTITION is not set\n"
"# CONFIG_ENV_IN_SERIAL is not set\n"
"# CONFIG_ENV_IN_MMC is not set\n"
"CONFIG_ENV_IN_NAND=y\n"
"# CONFIG_ENV_IN_UBI is not set\n"
"# CONFIG_ENV_IN_SERIAL_512K is not set\n"
"# CONFIG_ENV_IN_ERR is not set\n"
"# CONFIG_INFO_IN_UBI_FILE is not set\n"
"# CONFIG_INFO_IN_SERIAL_ENV is not set\n"
"# CONFIG_INFO_IN_MMC_ENV is not set\n"
"# CONFIG_INFO_IN_ERR is not set\n"
;
#endif /* _BBCONFIGOPTS_H */
