////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.2][Build:Apr  7 2010 20:56:42]
/////////////////////////////////////////////////////////////////////////////


#ifndef _MPLAYER_STRING_ENUMINDEX_H
#define _MPLAYER_STRING_ENUMINDEX_H

typedef enum
{
    English=0,
    Chinese_Sim=1,
    LANG_PAGE_MAX,

} LANG_PAGE_ENUM;

typedef enum
{
    Empty=0,
    en_str_Menu=1,
    en_str_VGA_Input_Text=2,
    en_str_Bri_Con_Text=3,
    en_str_Auto_Adjust=4,
    en_str_Input_Source=5,
    en_str_Color_Settings=6,
    en_str_Display_Settings=7,
    en_str_Other_Settings=8,
    en_str_Resolution=9,
    en_str_Mstar_Web_Site=10,
    en_strLL=11,
    en_str_Input_Color_Format=12,
    en_str_Preset_Modes=13,
    en_str_Super_Resolution=14,
    en_str_Aspect_Ratio=15,
    en_str_Horizontal_Position=16,
    en_str_Vertical_Position=17,
    en_str_Sharpness=18,
    en_str_Pixel_Clock=19,
    en_str_Phase=20,
    en_str_Language=21,
    en_str_Menu_Transparency=22,
    en_str_Menu_Rotation=23,
    en_str_Factory_Reset=24,
    en_str_RGB=25,
    en_str_YPbPr=26,
    en_str_Hue=27,
    en_str_Saturation=28,
    en_str_6500K=29,
    en_str_5700K=30,
    en_str_9300K=31,
    en_str_Movie=32,
    en_str_Game=33,
    en_str_Custom_Color=34,
    en_str_Wide_16By9=35,
    en_str_4By3=36,
    en_str_5By4=37,
    en_str_Brightness=38,
    en_str_Contrast=39,
    en_str_Dynamic_Contrast=40,
    en_str_Auto_Select=41,
    en_str_Source_VGA=42,
    en_str_Source_DVI=43,
    en_str_Source_HDMI=44,
    en_str_Source_DP=45,
    en_str_English=46,
    en_str_Chinese_Sim=47,
    en_str_Auto_Adjust_in_Progress=48,
    en_str_Out_Of_Range=49,
    en_str_Enter_Power_Save_Mode=50,
    en_str_No_VGA_Cable=51,
    en_str_Mstar=52,
    en_str_On=53,
    en_str_Off=54,
    en_str_CustomeR=55,
    en_str_CustomeG=56,
    en_str_CustomeB=57,
    en_str_DVI_D_Input=58,
    en_str_Multi_Window_Settings=59,
    en_str_Window_1=60,
    en_str_Window_2=61,
    en_str_Window_3=62,
    en_str_Window_4=63,
    en_str_Multi_Window_Modes=64,
    en_str_Window_Select=65,
    en_str_PIP_Size=66,
    en_str_PIP_Horizontal_Position=67,
    en_str_PIP_Vertical_Position=68,
    en_str_PIP_Mode=69,
    en_str_PBP_Mode_1=70,
    en_str_PBP_Mode_2=71,
    en_str_Triple_Mode=72,
    en_str_Quad_Mode=73,
    en_str_Small=74,
    en_str_Medium=75,
    en_str_Large=76,
    en_str_Huge=77,
    en_str_Window1=78,
    en_str_Window2=79,
    en_str_Window3=80,
    en_str_Window4=81,
    en_str_Auto=82,
    en_str_Full_Screen=83,
    en_str_One_By_One=84,
    en_str_HDMI_1=85,
    en_str_HDMI_2=86,
    en_str_Display_Port_1=87,
    en_str_Display_Port_2=88,
    en_str_Response_Time=89,
    en_str_Normal=90,
    en_str_Overdrive=91,
    en_str_No_HDMI_1_Cable=92,
    en_str_No_HDMI_2_Cable=93,
    en_str_No_Display_1_Port_Cable=94,
    en_str_No_Display_2_Port_Cable=95,
    en_str_No_DVI_1_Cable=96,
    en_str_No_DVI_2_Cable=97,
    en_str_No_Signal_Input=98,
    en_str_High=99,
    en_str_Middle=100,
    en_str_Low=101,
    E_ZUI_STR_MAX,

} OSDCP_EN_STRING_INDEX;

#endif    //_MPLAYER_STRING_ENUMINDEX_H

