////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.2][Build:Apr  7 2010 20:56:42]
/////////////////////////////////////////////////////////////////////////////


#ifndef _MPLAYER_BITMAP_ENUMINDEX_H
#define _MPLAYER_BITMAP_ENUMINDEX_H

#define MPLAYER_ARGB8888 (0)
#define MPLAYER_ARGB4444 (1)
#define MPLAYER_RGB565 (2)
#define MPLAYER_RGB555 (3)
#define MPLAYER_BLINK (4)
#define MPLAYER_I8 (5)
#define MPLAYER_ARGB1555 (6)


#define MPLAYER_PROJECT_PANEL_W  800
#define MPLAYER_PROJECT_PANEL_H  600

#define MPLAYER_BITMAP_FORMAT  (MPLAYER_ARGB1555)

#define MPLAYER_CLRKEY (0xFF000000)

#define MPLAYER_BMP_CLRKEY_LO (0xFF000000)
#define MPLAYER_BMP_CLRKEY_HI (0xFF000000)

#define MPLAYER_CLRKEY_R (0x00)
#define MPLAYER_CLRKEY_G (0x00)
#define MPLAYER_CLRKEY_B (0x00)

#define MPLAYER_TRANSPARENT_COLOR (0x00000000)



typedef enum
{
    E_BMP_SCREEN_SAVER_BG_DOT=0,
    E_BMP_MENU_LOGO_4C_20110524_=1,
    E_BMP_ITEM_FOCUS=2,
    E_BMP_ITEM_FOCUS_DOT=3,
    E_BMP_CHECK_MARK_TICK_2C_20130423=4,
    E_BMP_VOLUME_BALL_RED=5,
    E_BMP_EQ_BLUE_BAR=6,
    E_BMP_EQ_PURPLE_BAR=7,
    E_BMP_EQ_RED_BAR=8,
    E_BMP_GAUGEBARICON=9,
    E_BMP_SCROLLER_DOWN=10,
    E_BMP_SCROLLER_UP=11,
    E_BMP_VOLUME_BALL_BLUE=12,
    E_BMP_VOLUME_BALL_GRAY=13,
    E_BMP_VOLUME_BALL_GRAY_HIDE=14,
    E_BMP_VOLUME_BALL_PURPLE=15,
    E_BMP_MENU_IMG_LIST_PROGRESS=16,
    E_BMP_MENU_IMG_LIST_PROGRESS_NORMAL=17,
    E_BMP_CHECK_MARK_TICK_FOCUS=18,
    E_BMP_MSTAR_LOGO_20110516=19,
    E_ZUI_BMP_MAX,

} OSDCP_EN_BITMAP_INDEX;

#endif    //_MPLAYER_BITMAP_ENUMINDEX_H

