////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.2][Build:Apr  7 2010 20:56:42]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// AUTO_ADJUST_TRANSPARENT_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Auto_Adjust_Transparent_Bg_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_16 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DIRECT_MENU_AUTO_ADJUST_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Direct_Menu_Auto_Adjust_Bg_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DIRECT_MENU_AUTO_ADJUST_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Direct_Menu_Auto_Adjust_Text_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_0 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_195 },
    { CP_NOON, 0 },
};

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Auto_Adjust[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_AUTO_ADJUST_TRANSPARENT_BG
    { _Zui_Auto_Adjust_Transparent_Bg_Normal_DrawStyle, NULL, NULL     },

    // 2 = HWND_DIRECT_MENU_AUTO_ADJUST_BG
    { _Zui_Direct_Menu_Auto_Adjust_Bg_Normal_DrawStyle, NULL, NULL     },

    // 3 = HWND_DIRECT_MENU_AUTO_ADJUST_TEXT
    { _Zui_Direct_Menu_Auto_Adjust_Text_Normal_DrawStyle, NULL, NULL     },

};
