////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.2][Build:Apr  7 2010 20:56:42]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// TRANSPARENT_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Transparent_Bg_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DEFAULT_WNDPROC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Default_Wndproc_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_3 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Default_Wndproc_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_4 },
    { CP_NOON, 0 },
};
#define _Zui_Default_Wndproc_Disabled_DrawStyle _Zui_Default_Wndproc_Normal_DrawStyle

/////////////////////////////////////////////////////
// MARQUEE_WNDPROC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Marquee_Wndproc_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_2 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_193 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Marquee_Wndproc_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_5 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_193 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DYNAMICTEXT_WNDPROC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dynamictext_Wndproc_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_6 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_194 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Dynamictext_Wndproc_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_7 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_194 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DYNAMICPUNCTEXT_WNDPROC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dynamicpunctext_Wndproc_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_8 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_193 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Dynamicpunctext_Wndproc_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_9 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_193 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_2 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// ANIMATION_WNDPROC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Animation_Wndproc_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_5 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Animation_Wndproc_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_6 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DYNAMICCOLORTEXT_WNDPROC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dynamiccolortext_Wndproc_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_2 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_194 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Dynamiccolortext_Wndproc_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_5 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_194 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// BALLPROGRESSBAR_WNDPROC styles..

#define _Zui_Ballprogressbar_Wndproc_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
static DRAWSTYLE _MP_TBLSEG _Zui_Ballprogressbar_Wndproc_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_5 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// RECTPROGRESSBAR_WNDPROC styles..

#define _Zui_Rectprogressbar_Wndproc_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Rectprogressbar_Wndproc_Focus_DrawStyle _Zui_Ballprogressbar_Wndproc_Focus_DrawStyle

/////////////////////////////////////////////////////
// DYNAMICLIST_WNDPROC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dynamiclist_Wndproc_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_10 },
    { CP_NOON, 0 },
};
#define _Zui_Dynamiclist_Wndproc_Focus_DrawStyle _Zui_Ballprogressbar_Wndproc_Focus_DrawStyle

/////////////////////////////////////////////////////
// DYNAMICLIST_1 styles..

#define _Zui_Dynamiclist_1_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
static DRAWSTYLE _MP_TBLSEG _Zui_Dynamiclist_1_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_11 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Dynamiclist_1_Disabled_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_12 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DYNAMICLIST_2 styles..

#define _Zui_Dynamiclist_2_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Dynamiclist_2_Focus_DrawStyle _Zui_Dynamiclist_1_Focus_DrawStyle
#define _Zui_Dynamiclist_2_Disabled_DrawStyle _Zui_Ballprogressbar_Wndproc_Focus_DrawStyle

/////////////////////////////////////////////////////
// DYNAMICLIST_3 styles..

#define _Zui_Dynamiclist_3_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Dynamiclist_3_Focus_DrawStyle _Zui_Dynamiclist_1_Focus_DrawStyle
static DRAWSTYLE _MP_TBLSEG _Zui_Dynamiclist_3_Disabled_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_13 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DYNAMICBITMAP_WNDPROC styles..

#define _Zui_Dynamicbitmap_Wndproc_Normal_DrawStyle _Zui_Animation_Wndproc_Normal_DrawStyle
#define _Zui_Dynamicbitmap_Wndproc_Focus_DrawStyle _Zui_Animation_Wndproc_Focus_DrawStyle

/////////////////////////////////////////////////////
// KEYBOARDINPUT_WNDPROC styles..

#define _Zui_Keyboardinput_Wndproc_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Keyboardinput_Wndproc_Focus_DrawStyle _Zui_Ballprogressbar_Wndproc_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUTOCLOSE_WNDPROC styles..

#define _Zui_Autoclose_Wndproc_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Autoclose_Wndproc_Focus_DrawStyle _Zui_Ballprogressbar_Wndproc_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_WNDPROC styles..

#define _Zui_Effect_Wndproc_Normal_DrawStyle _Zui_Default_Wndproc_Normal_DrawStyle
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Wndproc_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// GRID_WNDPROC styles..

#define _Zui_Grid_Wndproc_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Grid_Wndproc_Focus_DrawStyle _Zui_Ballprogressbar_Wndproc_Focus_DrawStyle

/////////////////////////////////////////////////////
// GRID1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Grid1_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_14 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// GRID2 styles..

#define _Zui_Grid2_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid2_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID3 styles..

#define _Zui_Grid3_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid3_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID4 styles..

#define _Zui_Grid4_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid4_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID5 styles..

#define _Zui_Grid5_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid5_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID6 styles..

#define _Zui_Grid6_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid6_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID7 styles..

#define _Zui_Grid7_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid7_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID8 styles..

#define _Zui_Grid8_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid8_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID9 styles..

#define _Zui_Grid9_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid9_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID10 styles..

#define _Zui_Grid10_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid10_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID11 styles..

#define _Zui_Grid11_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid11_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID12 styles..

#define _Zui_Grid12_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid12_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID13 styles..

#define _Zui_Grid13_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid13_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID14 styles..

#define _Zui_Grid14_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid14_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// GRID15 styles..

#define _Zui_Grid15_Normal_DrawStyle _Zui_Grid1_Normal_DrawStyle
#define _Zui_Grid15_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// ANIMATION_GROUP styles..


/////////////////////////////////////////////////////
// ANIMATION_01 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Animation_01_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_2 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// ANIMATION_02 styles..

#define _Zui_Animation_02_Normal_DrawStyle _Zui_Animation_01_Normal_DrawStyle

/////////////////////////////////////////////////////
// ANIMATION_03 styles..

#define _Zui_Animation_03_Normal_DrawStyle _Zui_Animation_01_Normal_DrawStyle

/////////////////////////////////////////////////////
// ANIMATION_04 styles..

#define _Zui_Animation_04_Normal_DrawStyle _Zui_Animation_01_Normal_DrawStyle

/////////////////////////////////////////////////////
// ANIMATION_05 styles..

#define _Zui_Animation_05_Normal_DrawStyle _Zui_Animation_01_Normal_DrawStyle

/////////////////////////////////////////////////////
// ANIMATION_06 styles..

#define _Zui_Animation_06_Normal_DrawStyle _Zui_Animation_01_Normal_DrawStyle

/////////////////////////////////////////////////////
// ANIMATION_07 styles..

#define _Zui_Animation_07_Normal_DrawStyle _Zui_Animation_01_Normal_DrawStyle

/////////////////////////////////////////////////////
// ANIMATION_08 styles..

#define _Zui_Animation_08_Normal_DrawStyle _Zui_Animation_01_Normal_DrawStyle

/////////////////////////////////////////////////////
// RNGGRADIENT1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Rnggradient1_Normal_DrawStyle[] =
{
    { CP_RECT, CP_ZUI_RECT_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// BUTTON_CLICK_SAMPLE styles..

#define _Zui_Button_Click_Sample_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Button_Click_Sample_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Button_Click_Sample_Disabled_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// BUTTON_CLICK styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Button_Click_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_2 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_1 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Button_Click_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_10 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_1 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Button_Click_Disabled_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_10 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// ROTATE_STATIC_SAMPLE styles..

#define _Zui_Rotate_Static_Sample_Normal_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Rotate_Static_Sample_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle
#define _Zui_Rotate_Static_Sample_Disabled_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// ROTATE_STATIC_1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Rotate_Static_1_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_0 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_1 },
    { CP_NOON, 0 },
};
#define _Zui_Rotate_Static_1_Focus_DrawStyle _Zui_Rotate_Static_1_Normal_DrawStyle
static DRAWSTYLE _MP_TBLSEG _Zui_Rotate_Static_1_Disabled_DrawStyle[] =
{
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DYNAMICTEXT_EFFECT styles..

#define _Zui_Dynamictext_Effect_Normal_DrawStyle _Zui_Marquee_Wndproc_Normal_DrawStyle
#define _Zui_Dynamictext_Effect_Focus_DrawStyle _Zui_Dynamicpunctext_Wndproc_Normal_DrawStyle
#define _Zui_Dynamictext_Effect_Disabled_DrawStyle _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle

/////////////////////////////////////////////////////
// TEST1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Test1_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_15 },
    { CP_NOON, 0 },
};
#define _Zui_Test1_Focus_DrawStyle _Zui_Test1_Normal_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Idle[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_TRANSPARENT_BG
    { _Zui_Transparent_Bg_Normal_DrawStyle, NULL, NULL     },

    // 2 = HWND_DEFAULT_WNDPROC
    { _Zui_Default_Wndproc_Normal_DrawStyle, _Zui_Default_Wndproc_Focus_DrawStyle, _Zui_Default_Wndproc_Disabled_DrawStyle     },

    // 3 = HWND_MARQUEE_WNDPROC
    { _Zui_Marquee_Wndproc_Normal_DrawStyle, _Zui_Marquee_Wndproc_Focus_DrawStyle, NULL     },

    // 4 = HWND_DYNAMICTEXT_WNDPROC
    { _Zui_Dynamictext_Wndproc_Normal_DrawStyle, _Zui_Dynamictext_Wndproc_Focus_DrawStyle, NULL     },

    // 5 = HWND_DYNAMICPUNCTEXT_WNDPROC
    { _Zui_Dynamicpunctext_Wndproc_Normal_DrawStyle, _Zui_Dynamicpunctext_Wndproc_Focus_DrawStyle, _Zui_Dynamicpunctext_Wndproc_Disabled_DrawStyle     },

    // 6 = HWND_ANIMATION_WNDPROC
    { _Zui_Animation_Wndproc_Normal_DrawStyle, _Zui_Animation_Wndproc_Focus_DrawStyle, NULL     },

    // 7 = HWND_DYNAMICCOLORTEXT_WNDPROC
    { _Zui_Dynamiccolortext_Wndproc_Normal_DrawStyle, _Zui_Dynamiccolortext_Wndproc_Focus_DrawStyle, NULL     },

    // 8 = HWND_BALLPROGRESSBAR_WNDPROC
    { _Zui_Ballprogressbar_Wndproc_Normal_DrawStyle, _Zui_Ballprogressbar_Wndproc_Focus_DrawStyle, NULL     },

    // 9 = HWND_RECTPROGRESSBAR_WNDPROC
    { _Zui_Rectprogressbar_Wndproc_Normal_DrawStyle, _Zui_Rectprogressbar_Wndproc_Focus_DrawStyle, NULL     },

    // 10 = HWND_DYNAMICLIST_WNDPROC
    { _Zui_Dynamiclist_Wndproc_Normal_DrawStyle, _Zui_Dynamiclist_Wndproc_Focus_DrawStyle, NULL     },

    // 11 = HWND_DYNAMICLIST_1
    { _Zui_Dynamiclist_1_Normal_DrawStyle, _Zui_Dynamiclist_1_Focus_DrawStyle, _Zui_Dynamiclist_1_Disabled_DrawStyle     },

    // 12 = HWND_DYNAMICLIST_2
    { _Zui_Dynamiclist_2_Normal_DrawStyle, _Zui_Dynamiclist_2_Focus_DrawStyle, _Zui_Dynamiclist_2_Disabled_DrawStyle     },

    // 13 = HWND_DYNAMICLIST_3
    { _Zui_Dynamiclist_3_Normal_DrawStyle, _Zui_Dynamiclist_3_Focus_DrawStyle, _Zui_Dynamiclist_3_Disabled_DrawStyle     },

    // 14 = HWND_DYNAMICBITMAP_WNDPROC
    { _Zui_Dynamicbitmap_Wndproc_Normal_DrawStyle, _Zui_Dynamicbitmap_Wndproc_Focus_DrawStyle, NULL     },

    // 15 = HWND_KEYBOARDINPUT_WNDPROC
    { _Zui_Keyboardinput_Wndproc_Normal_DrawStyle, _Zui_Keyboardinput_Wndproc_Focus_DrawStyle, NULL     },

    // 16 = HWND_AUTOCLOSE_WNDPROC
    { _Zui_Autoclose_Wndproc_Normal_DrawStyle, _Zui_Autoclose_Wndproc_Focus_DrawStyle, NULL     },

    // 17 = HWND_EFFECT_WNDPROC
    { _Zui_Effect_Wndproc_Normal_DrawStyle, _Zui_Effect_Wndproc_Focus_DrawStyle, NULL     },

    // 18 = HWND_GRID_WNDPROC
    { _Zui_Grid_Wndproc_Normal_DrawStyle, _Zui_Grid_Wndproc_Focus_DrawStyle, NULL     },

    // 19 = HWND_GRID1
    { _Zui_Grid1_Normal_DrawStyle, NULL, NULL     },

    // 20 = HWND_GRID2
    { _Zui_Grid2_Normal_DrawStyle, _Zui_Grid2_Focus_DrawStyle, NULL     },

    // 21 = HWND_GRID3
    { _Zui_Grid3_Normal_DrawStyle, _Zui_Grid3_Focus_DrawStyle, NULL     },

    // 22 = HWND_GRID4
    { _Zui_Grid4_Normal_DrawStyle, _Zui_Grid4_Focus_DrawStyle, NULL     },

    // 23 = HWND_GRID5
    { _Zui_Grid5_Normal_DrawStyle, _Zui_Grid5_Focus_DrawStyle, NULL     },

    // 24 = HWND_GRID6
    { _Zui_Grid6_Normal_DrawStyle, _Zui_Grid6_Focus_DrawStyle, NULL     },

    // 25 = HWND_GRID7
    { _Zui_Grid7_Normal_DrawStyle, _Zui_Grid7_Focus_DrawStyle, NULL     },

    // 26 = HWND_GRID8
    { _Zui_Grid8_Normal_DrawStyle, _Zui_Grid8_Focus_DrawStyle, NULL     },

    // 27 = HWND_GRID9
    { _Zui_Grid9_Normal_DrawStyle, _Zui_Grid9_Focus_DrawStyle, NULL     },

    // 28 = HWND_GRID10
    { _Zui_Grid10_Normal_DrawStyle, _Zui_Grid10_Focus_DrawStyle, NULL     },

    // 29 = HWND_GRID11
    { _Zui_Grid11_Normal_DrawStyle, _Zui_Grid11_Focus_DrawStyle, NULL     },

    // 30 = HWND_GRID12
    { _Zui_Grid12_Normal_DrawStyle, _Zui_Grid12_Focus_DrawStyle, NULL     },

    // 31 = HWND_GRID13
    { _Zui_Grid13_Normal_DrawStyle, _Zui_Grid13_Focus_DrawStyle, NULL     },

    // 32 = HWND_GRID14
    { _Zui_Grid14_Normal_DrawStyle, _Zui_Grid14_Focus_DrawStyle, NULL     },

    // 33 = HWND_GRID15
    { _Zui_Grid15_Normal_DrawStyle, _Zui_Grid15_Focus_DrawStyle, NULL     },

    // 34 = HWND_ANIMATION_GROUP
    { NULL, NULL, NULL     },

    // 35 = HWND_ANIMATION_01
    { _Zui_Animation_01_Normal_DrawStyle, NULL, NULL     },

    // 36 = HWND_ANIMATION_02
    { _Zui_Animation_02_Normal_DrawStyle, NULL, NULL     },

    // 37 = HWND_ANIMATION_03
    { _Zui_Animation_03_Normal_DrawStyle, NULL, NULL     },

    // 38 = HWND_ANIMATION_04
    { _Zui_Animation_04_Normal_DrawStyle, NULL, NULL     },

    // 39 = HWND_ANIMATION_05
    { _Zui_Animation_05_Normal_DrawStyle, NULL, NULL     },

    // 40 = HWND_ANIMATION_06
    { _Zui_Animation_06_Normal_DrawStyle, NULL, NULL     },

    // 41 = HWND_ANIMATION_07
    { _Zui_Animation_07_Normal_DrawStyle, NULL, NULL     },

    // 42 = HWND_ANIMATION_08
    { _Zui_Animation_08_Normal_DrawStyle, NULL, NULL     },

    // 43 = HWND_RNGGRADIENT1
    { _Zui_Rnggradient1_Normal_DrawStyle, NULL, NULL     },

    // 44 = HWND_BUTTON_CLICK_SAMPLE
    { _Zui_Button_Click_Sample_Normal_DrawStyle, _Zui_Button_Click_Sample_Focus_DrawStyle, _Zui_Button_Click_Sample_Disabled_DrawStyle     },

    // 45 = HWND_BUTTON_CLICK
    { _Zui_Button_Click_Normal_DrawStyle, _Zui_Button_Click_Focus_DrawStyle, _Zui_Button_Click_Disabled_DrawStyle     },

    // 46 = HWND_ROTATE_STATIC_SAMPLE
    { _Zui_Rotate_Static_Sample_Normal_DrawStyle, _Zui_Rotate_Static_Sample_Focus_DrawStyle, _Zui_Rotate_Static_Sample_Disabled_DrawStyle     },

    // 47 = HWND_ROTATE_STATIC_1
    { _Zui_Rotate_Static_1_Normal_DrawStyle, _Zui_Rotate_Static_1_Focus_DrawStyle, _Zui_Rotate_Static_1_Disabled_DrawStyle     },

    // 48 = HWND_DYNAMICTEXT_EFFECT
    { _Zui_Dynamictext_Effect_Normal_DrawStyle, _Zui_Dynamictext_Effect_Focus_DrawStyle, _Zui_Dynamictext_Effect_Disabled_DrawStyle     },

    // 49 = HWND_TEST1
    { _Zui_Test1_Normal_DrawStyle, _Zui_Test1_Focus_DrawStyle, NULL     },

};
